CREATE TABLE `productos` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `nombre_producto` VARCHAR(255),
  `seccion` VARCHAR(255),
  `pais_origen` VARCHAR(255),
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);
